require File.expand_path('../../config/environment', __FILE__)
products = [
['Cinco MIDI Organizer', 'A hardware device for non-GUI PCs that organizes MIDI audio files by assigning very long access numbers to them.'],
['T\'ird', 'A feathered flying disc that resembles a combination of a bird and a turtle. It can fly up to half a mile, and then use its turtle legs to slowly crawl back to its user.'],
['B\'owl','A stuffed animal that resembles a combination of a bat and an owl.'],
['B\'ougar','A stuffed bear with the growl of a cougar.'],
['Cinco-Fone','A one button, dual-antenna cell phone that can only place calls and has only enough battery power to make one call. Due to its high operating temperature, it comes with a tube of cooling gel that can be applied to the face. Endorsed by Ed Begley, Jr.'],
['Cinco Long Distance','A not-so-easy-to-use long distance telephone service provider.'],
['Cinco International Credit Union Personal Banking Center','A not-so-easy-to-use automated personal banking service featuring One Touch Banking, Easy Interface, No Human Interaction and Sanitary Personal Touch Environment. May change your wife\'s legal name to Taargüs Taargüs.'],
['Candy Tails', 'Horse hair extensions for children to wear, coated in candy flavors for sucking on.'],
['My New Pep-Pep', 'A life-size grandfather doll, including scent packs to smell like a real grandfather.'],
['The Best of James Quall', 'A three VHS set of James Quall impressions. A special offer includes 200 hours of bonus material.'],
['Thocks','A pair of business socks that are fashioned like thong underwear.'],
['Cinco Boy','A life-size son doll, which is periodically replaced with larger, "older" dolls. Endorsed by Peter Stormare (aka "Gorb").'],
['Encyclopedia of Numbers A single volume containing "all of the numbers imaginable". Endorsed by Rainn Wilson.'],
['Innernette  A mini CD that contains several programs that are meant to simulate the experience of the Internet.'],
['D\'ump','A digital baseball umpire in the form of a talking deer statue. It warns users of bear attacks by shutting down.'],
['Balls Insurance','Insurance coverage for being struck in the testicles.'],
['It\'s Not Jackie Chan','A board game in which players must "guess things that are not Jackie Chan".'],
['My Eggs', 'Pills that, when ingested, convert the user\'s feces to edible eggs with neon-colored yolks. Includes a nest to "lay" the eggs in. Endorsed by Steve Schirripa'],
['C-Bund',' A cummerbund worn as a replacement for pants and underwear (thus simply exposing the genitals).'],
['Cinco Video Cube Playback System', 'A large, cube-shaped device which contains a movie. Must be plugged into a VHS tape with a bulky adapter cable and played on a "Cinco VHS Playback System"'],
['Cigarette Juice','A beverage derived from filtering water through the pulverized contents of cigarettes. Endorsed by Spagett.'],
['Cinco E-Trial','A method of inaccurately and inefficiently being put on trial via software, in which the defendant selects their own e-jury and is responsible for presenting any evidence against themselves. Apparently legally binding, it successfully convicted one of the Cinco Brothers for murder.'],
['Urinal Shower','A small pipe that redirects a urinal\'s flushing water to allow showering in any public restroom.'],
['Mancierge','A cell phone that only dials Fred Willard, who singlehandedly dispenses live advice to all of the system\'s users at once.'],
['D-Pants','Watertight plastic pants meant to be worn beneath one\'s normal pants to keep large amounts of uncontrollable diarrhea contained.'],
['Cinco Napple','An apple coated with "sleeping gel" to cause its eater to fall asleep, and injected with a bowel irritant to end the nap after 15 minutes. Due to this fact, it is recommended that they be used with the D-Pants. Endorsed by Alan Thicke.'],
['Groban Sings Casey','Josh Groban\'s six cassette tribute to deceased Uncle Muscles Hour performer Casey.'],
['Diarrheaphragm', 'A fecal dam inserted into the colon to prevent instances of uncontrollable diarrhea.'],
['i-Jammer and E-Bumper', 'A digital music box for children with two "revolutionary dance tones", which have similar effects to an addictive recreational drug. Progress can be tracked in real time by other users, and the device also features "Oh Hungee", a dispenser of a paste food source. The advertisement contains several disclaimers, one of which warning that "eBumping is not safe for pets or children."'],
['Man Shake', 'A drink made from water and pubic hair to accelerate puberty ("grow a lush pube mound").'],
['Man Nip', 'A catnip-like product to revitalize old men. Endorsed by Patrick Duffy.'],
['H\'amb', 'An affordable meat product made by kneading the essence of lamb into a loaf of ham. Includes "lamb-scented spray."'],
['H\'ambster','Similar to H\'amb, is faux shellfish, manufactured from pork byproducts H\'ambster mimics the appearance and flavor of lobster.'],
['Cinco Sleepwatching', 'Chair A chair designed for people to watch their friends sleep. Comes with built-in zoom lens, dreamer\'s book, Nightmare Prevention device, toilet, and electroshock system to prevent the user from falling asleep themselves.'],
['Musky Tusk','Necklace A necklace designed to give good luck by rubbing dead animals on it.'],
['Cinco Face Time Party Snoozer', 'A sleep mask designed to make its wearer be able to sleep at a party while still appearing awake. It includes a stand to hold the user in a standing position, and can play professionally recorded voice clips of common phrases to allow the user to seemingly communicate with other guests.'],
['The Tairy Greene Machine','A digital jukebox containing every movie, commercial, and public appearance Tairy Greene has ever made. The device requires the use of Tairy Tokens to play its content, which cost $39.99 USD each. The device also utilizes "Greene Technology"—it is powered by tap water which must be heated to exactly 75° F (despite being incompatible with most sinks), which is deposited out the back of the machine after use (mops are also included for cleanup)'],
['Cinco Privacy Helmet', 'An enormous helmet that can emit a loud ear-piercing frequency, and sprays mace in the user\'s eyes so they cannot hear or see what is going on. "Cinco presents a new roommate privacy device. HI-TECH TONES BLOCK ALL EXTERIOR SOUND. BLINDING MACE TEMPORARILY BLURS VISION. E-Z FIT HELMET FOR ALL HEAD SIZES." Cinco helps your friends bang girls in your dorm.'],
['Cinco Mouth Decorator', 'A kit that allows its user to attach jewels to their face using an included hot glue gun, and a hairdryer with a full face attachment to dry the jewels in place.'],
['Cinco Pasta Bear','A teddy bear stuffed with Italian-style pasta, designed to be given as a "Chrimbus" gift. To prepare the pasta inside, the bear must be boiled overnight, microwaved for 45 minutes, cut open with a knife, and the pasta removed and inspected for surviving insects or larvae.'],
['CincoEdit','Editing Software used by Tim and Eric the make DUMPERS - a tim & eric film their alleged "first video" "Snow."'],
['Cinco Foto Fiddler','A software application which allows users to upload pictures to the web.'],
['Eye Tanning System','A complicated process to get rid of \'raccoon eyes\' caused by tanning with sunglasses. Requires the user have all their teeth extracted as part of the process.'],
['E-Z Kreme','A skin cream infused with a laxative targeted towards missing valuable time, meetings, and other important events.'],
['Bro-oche','A brooch tailored for men. Designed to be screwed directly into a hole placed in the wearer\'s body, the creation of which requires removal of the wearer\'s teeth.'],
['Cinco Food Tube','A system for fast ingestion of food, avoiding the dangers of utensils. Requires the users\' teeth to be removed and a plastic tube inserted from the mouth to the stomach. Regular food is thrown into a large machine that blends the food into a liquid, which then forces it into the user\'s mouth via a large plastic tube.'],
['Wait-mate','A pill which makes the user sleep for a few days. It\'s used when the user is looking forward to something in the future but can\'t wait. Endorsed by Jeff Goldblum.'],
]

products.each do |name, desc|
  Spree::Product.create(:name => name, :description => desc, :price => rand*100.0, :shipping_category => Spree::ShippingCategory.first)
end
